# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 武陵元氣營 | 志工團隊
email: yuanchi.wlsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  武陵元氣營2.0網站
  武陵元氣營，由武陵高中的學生自組而成，每年暑假到偏鄉國小服務，希望帶給小朋友不同於課本的知識。
baseurl: "/yuanchi" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: 武陵高中元氣營
address_line: 桃園市立武陵高級中學
company_email: yuanchi.wlsh@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144

# Social Link
facebook_link: https://www.facebook.com/yuanchicamp/
instagram_link: https://www.instagram.com/yuanchipupu/?hl=zh-tw
youtube_link: https://www.youtube.com/channel/UC4LH4MdIguNMA9z3MWhGPMg

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
